Add clearTerminal setting
jest-community/vscode-jest pull request #1014
Opened 2023-03-22 19:43 UTC by jgillick

When auto-run is disabled, it's convenient to have the terminal clear and only show the results from the most recent run.

In this PR:
* Added a `clearTerminal` boolean setting.
* Added `clear()` to `ExtOutputTerminal`
* Clears the terminal when a test run is scheduled if the setting is set to `true`.

2023-04-30 20:20 UTC, connectdotz reviewed
@jgillick Thanks for the PR, I think this is a useful feature. Sorry about the delayed response.

A few comments:
1. let's change the setting to "autoClearTerminal".
2. This probably only worked for the interactive runs, which is fine. But if we can find a way to make it also work for "watch" mode, that will be even better. The "watch" mode doesn't go through the "schedule" call as it is initiated outside of vscode. But it did emit other signals... see the `process-isteners` code for clues.

2023-05-29 18:13 UTC, jgillick commented
Thanks for the feedback.
* I've updated the setting name to `autoClearTerminal`
* It will now also auto-clear when in watch mode. (basically anytime it logs `> Test run started`)

2023-06-10 02:31 UTC, connectdotz reviewed
Hey, thanks for the update. The code's looking good, but we need to improve the test coverage for the new changes. After all, this is a test extension, right? We gotta walk the talk! 😄

When you get a chance, could you also update the [Customization](https://github.com/jest-community/vscode-jest#customization) section in the README.md?

Apologies for the slow response on my end. This is a super useful change, and once those updates are made, I'll be ready to merge it in. Thanks again!

2023-06-22 02:33 UTC, connectdotz requested changes
Thanks for the update. Looks like there are some merge issues. Please see the comment.

BTW, you can `yarn run ci` before check-in to ensure the tests and formats are correct before check-in.

2023-06-22 02:33 UTC, connectdotz commented on src/JestExt/helper.ts
> +    autoClearTerminal: config.get<boolean>('autoClearTerminal') ?? false,
please use `getSetting<boolean>` instead

2023-06-22 17:38 UTC, jgillick commented
Whoops, sorry about that. It should be resolved now.

2023-06-25 17:10 UTC, connectdotz requested changes
It seems that maybe a test is accidentally deleted?

2023-06-25 17:10 UTC, connectdotz commented on tests/test-provider/test-item-data.test.ts
> -      });
Is this an intentional deletion or merge error?

2023-07-02 17:15 UTC, merged

2023-07-02 17:15 UTC, connectdotz commented
Thanks for the PR!