fix testPathPattern for virtual folders
jest-community/vscode-jest pull request #1080
Opened 2023-10-13 20:09 UTC by akwodkiewicz

This PR fixes jest-community/vscode-jest#1079

2023-10-14 21:20 UTC, connectdotz requested changes
@akwodkiewicz, Thanks for the PR! The change looks good, but let's create some tests to safeguard this use case.

2023-10-16 07:23 UTC, akwodkiewicz commented
Sure thing. I wanted to ask for help in how to write them, but I think I'll be able to pull off a unit test for `WorkspaceRoot.createTestItem` :+1:

2023-10-17 08:21 UTC, akwodkiewicz commented
The PR is ready for a another review

2023-10-22 18:01 UTC, connectdotz approved these changes
Thanks for updating the tests.

2023-10-22 18:01 UTC, merged